[tool.black]
line-length = 120
include = '\.pyi?$'
exclude = '''
(
  /(
      \.eggs         # exclude a few common directories in the
    | \.git          # root of the project
    | \.hg
    | \.mypy_cache
    | \.tox
    | \.venv
    | _build
    | buck-out
    | build
    | dist
  )/
  | docs/build/
  | node_modules/
  | venve/
  | .venv/
)
'''

[tool.nbqa.mutate]
isort = 1
black = 1

[tool.poetry]
name = "pytorch_forecasting"
readme = "README.md"  # Markdown files are supported
version = "0.0.0"  # is being replaced automatically

authors = ["Jan Beitner"]
classifiers = [
    "Intended Audience :: Developers",
    "Intended Audience :: Science/Research",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.6",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Topic :: Scientific/Engineering",
    "Topic :: Scientific/Engineering :: Mathematics",
    "Topic :: Scientific/Engineering :: Artificial Intelligence",
    "Topic :: Software Development",
    "Topic :: Software Development :: Libraries",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "License :: OSI Approved :: MIT License"]
description = "Forecasting timeseries with PyTorch - dataloaders, normalizers, metrics and models"
repository = "https://github.com/jdb78/pytorch-forecasting"
documentation = "https://pytorch-forecasting.readthedocs.io"
homepage = "https://pytorch-forecasting.readthedocs.io"

[tool.poetry.dependencies]
python = "^3.7.1"

torch = "^1.7"
pytorch-lightning = "^1.2.4"
optuna = "^2.3.0"
scipy = "*"
pandas = "^1.3.0"
scikit-learn = ">=0.24,<1.1"
matplotlib = "*"
statsmodels = "*"

pytest-github-actions-annotate-failures = {version = "*", optional = true}

[tool.poetry.dev-dependencies]
# checks and make tools
pre-commit = "^2.16.0"

invoke = "*"
flake8 = "*"
mypy = "*"
pylint = "*"
isort = "*"

# pytest
pytest = "*"
pytest-xdist = "*"
pytest-cov = "*"
pytest-sugar = "*"
coverage = "*"
pyarrow = "*"

# jupyter notebook
ipykernel = "*"
black = { version = "*", allow-prereleases = true, extras = ["jupyter"] }

# documentatation
sphinx = "*"
pydata-sphinx-theme = "*"
nbsphinx = "*"
pandoc = "*"
recommonmark = "*"


[tool.poetry.extras]  # extras
github-actions = ["pytest-github-actions-annotate-failures"]

[tool.poetry-dynamic-versioning]
enable = true
vcs = "git"
dirty = false
style = "semver"  # semantic versioning

[build-system]  # make the package pip installable
requires = ["poetry-core>=1.0.7", "poetry-dynamic-versioning>=0.13.1"]
build-backend = "poetry.core.masonry.api"
